# Generated by Django 4.2.23 on 2025-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
    ]
